name: Build
on:
  push:
    branches:
      - master
jobs:
  bulid-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: submodules
        run: git submodule update --init --recursive

      - name: Set vcpkg's response file path used as part of cache's key.
        uses: lukka/set-shell-env@v1
        with:
          vcpkgResponseFile: ${{ github.workspace }}\scripts\vcpkgs.txt

      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
          vcpkgDirectory: '${{ github.workspace }}\vcpkg'
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}

      - name: cmake-vs
        run: .\scripts\cmake-vs.ps1
      - name: build-plugins
        run: .\scripts\build-plugins.ps1